spring.application.name=identity-service

spring.datasource.url=jdbc:postgresql://localhost:5432/companyDB
spring.datasource.username=postgres
spring.datasource.password=REDACTED_DB_PASSWORD

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.servlet.context-path=/api/v1
jwt.secretKey=wdergrgrgthththtynjrtbhrtgbtrffrfttrgfgg