spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:

            - id: NOVEL-SERVICE-ROOT
              uri: ${NOVEL_SERVICE_URL:https://novel-service.onrender.com}
              predicates:
                - Path=/api/v1/novels
              filters:
                - SetPath=/novels

            - id: NOVEL-SERVICE
              uri: ${NOVEL_SERVICE_URL:https://novel-service.onrender.com}
              predicates:
                - Path=/api/v1/novels/**
              filters:
                - RewritePath=/api/v1/novels(?<segment>/.*), /novels${segment}

            - id: IDENTITY-SERVICE-ROOT
              uri: ${IDENTITY_SERVICE_URL:https://identity-service-0jgj.onrender.com}
              predicates:
                - Path=/api/v1/identity
              filters:
                - SetPath=/

            - id: IDENTITY-SERVICE
              uri: ${IDENTITY_SERVICE_URL:https://identity-service-0jgj.onrender.com}
              predicates:
                - Path=/api/v1/identity/**
              filters:
                - RewritePath=/api/v1/identity(?<segment>/.*), ${segment}

            - id: NOTIFICATION-SERVICE-ROOT
              uri: ${NOTIFICATION_SERVICE_URL:https://notification-service-ng1j.onrender.com}
              predicates:
                - Path=/api/v1/notifications
              filters:
                - SetPath=/

            - id: NOTIFICATION-SERVICE
              uri: ${NOTIFICATION_SERVICE_URL:https://notification-service-ng1j.onrender.com}
              predicates:
                - Path=/api/v1/notifications/**
              filters:
                - RewritePath=/api/v1/notifications(?<segment>/.*), ${segment}

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway

  endpoint:
    gateway:
      access: read-only

logging:
  level:
    org.springframework.cloud.gateway: DEBUG