// Comprehensive Dummy Novels for NovelForge Catalog
// Mirrors backend novel-service data model: { id, title, synopsis, categoryType, createdAt, updatedAt }
// Designed with 'Author Unknown' and '0 Chapters' to align with the current novel-service state.

export const DUMMY_NOVELS = [
  {
    id: 'dummy-1',
    title: 'Shadows of the Astral Realm',
    author: 'Author Unknown',
    categoryType: 'FICTION',
    synopsis: 'A fallen prodigy discovers an ancient forbidden scroll that binds cosmic constellations to his spirit soul. Facing ancient clans and sect rivalries, he embarks on an arduous ascension path to uncover primordial secrets.',
    rating: 4.9,
    views: '124K',
    chapters: 0,
    chapterStatus: 'No chapters published yet',
    createdAt: '2026-09-15T10:30:00Z',
    updatedAt: '2026-10-02T14:20:00Z',
    gradient: 'linear-gradient(135deg, #1e3a8a, #3b82f6)',
    isDummy: true,
  },
  {
    id: 'dummy-2',
    title: 'Cyberpunk Odyssey 2099',
    author: 'Author Unknown',
    categoryType: 'FICTION',
    synopsis: 'In a rain-drenched megacity governed by neural AI overlords, a rogue data smuggler uncovers a fatal glitch in humanity uploaded consciousness grid.',
    rating: 4.8,
    views: '98K',
    chapters: 0,
    chapterStatus: 'No chapters published yet',
    createdAt: '2026-09-18T08:15:00Z',
    updatedAt: '2026-10-04T11:45:00Z',
    gradient: 'linear-gradient(135deg, #4c1d95, #8b5cf6)',
    isDummy: true,
  },
  {
    id: 'dummy-3',
    title: 'The Alchemist of Forgotten Stars',
    author: 'Author Unknown',
    categoryType: 'FICTION',
    synopsis: 'When modern potion brewing meets high fantasy system progression, one forgotten craft turns the tides of war across seven celestial empires.',
    rating: 4.95,
    views: '210K',
    chapters: 0,
    chapterStatus: 'No chapters published yet',
    createdAt: '2026-09-20T12:00:00Z',
    updatedAt: '2026-10-05T16:10:00Z',
    gradient: 'linear-gradient(135deg, #065f46, #10b981)',
    isDummy: true,
  },
  {
    id: 'dummy-4',
    title: 'Chronicles of the Broken Throne',
    author: 'Author Unknown',
    categoryType: 'FICTION',
    synopsis: 'Seven kingdoms collide under the omen of the twin moons. Betrayal, honor, and ancient beasts awaken to reshape the geopolitical map of the Old World.',
    rating: 4.7,
    views: '86K',
    chapters: 0,
    chapterStatus: 'No chapters published yet',
    createdAt: '2026-09-22T09:40:00Z',
    updatedAt: '2026-10-01T18:30:00Z',
    gradient: 'linear-gradient(135deg, #7c2d12, #ea580c)',
    isDummy: true,
  },
  {
    id: 'dummy-5',
    title: 'Architecting Distributed Cloud Systems',
    author: 'Author Unknown',
    categoryType: 'NONFICTION',
    synopsis: 'A comprehensive handbook exploring enterprise microservices, reactive event streaming, container orchestration, and fault-tolerant cloud architectures.',
    rating: 4.92,
    views: '64K',
    chapters: 0,
    chapterStatus: 'No chapters published yet',
    createdAt: '2026-09-25T14:00:00Z',
    updatedAt: '2026-10-03T09:15:00Z',
    gradient: 'linear-gradient(135deg, #0f766e, #14b8a6)',
    isDummy: true,
  },
  {
    id: 'dummy-6',
    title: 'Echoes of the Abyssal Core',
    author: 'Author Unknown',
    categoryType: 'FICTION',
    synopsis: 'Deep ocean surveyors breach a hydrothermal rift only to wake a dormant biomechanical leviathan civilization sleeping beneath the seabed.',
    rating: 4.85,
    views: '73K',
    chapters: 0,
    chapterStatus: 'No chapters published yet',
    createdAt: '2026-09-28T11:20:00Z',
    updatedAt: '2026-10-06T15:50:00Z',
    gradient: 'linear-gradient(135deg, #312e81, #6366f1)',
    isDummy: true,
  },
  {
    id: 'dummy-7',
    title: 'The Art of Modern Narrative Craft',
    author: 'Author Unknown',
    categoryType: 'NONFICTION',
    synopsis: 'Exploring character dynamics, narrative tension, reader psychology, and pacing strategies for digital serialized web fiction authors.',
    rating: 4.88,
    views: '45K',
    chapters: 0,
    chapterStatus: 'No chapters published yet',
    createdAt: '2026-10-01T13:10:00Z',
    updatedAt: '2026-10-05T12:00:00Z',
    gradient: 'linear-gradient(135deg, #831843, #ec4899)',
    isDummy: true,
  },
  {
    id: 'dummy-8',
    title: 'Reincarnation of the Void Sovereign',
    author: 'Author Unknown',
    categoryType: 'FICTION',
    synopsis: 'Betrayed by divine pantheons at the pinnacle of power, the Void Sovereign reawakens three centuries earlier in the mortal body of an exiled noble.',
    rating: 4.91,
    views: '180K',
    chapters: 0,
    chapterStatus: 'No chapters published yet',
    createdAt: '2026-10-03T17:45:00Z',
    updatedAt: '2026-10-07T10:30:00Z',
    gradient: 'linear-gradient(135deg, #581c87, #c084fc)',
    isDummy: true,
  },
];

export const NOVEL_GRADIENTS = [
  'linear-gradient(135deg, #1e3a8a, #3b82f6)',
  'linear-gradient(135deg, #4c1d95, #8b5cf6)',
  'linear-gradient(135deg, #065f46, #10b981)',
  'linear-gradient(135deg, #7c2d12, #ea580c)',
  'linear-gradient(135deg, #312e81, #6366f1)',
  'linear-gradient(135deg, #581c87, #c084fc)',
  'linear-gradient(135deg, #0f766e, #14b8a6)',
  'linear-gradient(135deg, #831843, #ec4899)',
];
